---
- name: Converge Dev Workstation
  hosts: all
  pre_tasks:
    - name: Put runtime programs
      copy:
        src: files/{{ item }}
        dest: /bin/{{ item }}
        mode: 0755
        owner: root
        group: root
      with_items:
        - docker-entrypoint.sh
  roles:
    - role: NerdsvilleCEO.ansible_role_common
      vars:
        primary_user: "{{ default_user }}"
        primary_group: "{{ default_user }}"
